language: java
sudo: false
install: true
jdk:
  - openjdk8
script:
  - mvn clean install -Dgpg.skip -Dmaven.source.skip=true -Dmaven.javadoc.skip=true
cache:
  directories:
    - '$HOME/.m2/repository'

  
