language: java
sudo: false
install: true

addons:
    sonarcloud:
        organization: "jslsolucoes-github"
        branches:
            - develop
            - master
        token:
            secure: "qBYYcz94BI1vUjLT3G26rnS+oi3la4JxWg7gmo7uUvnh1b95qRijqZIxW5PKLRbGtCR7FA+MWi+BtZWmZx/dy1zM/t5J7d2JAq+y7p7ZVCj9Ozd5yVI7QSFNdrta/Tj+mnK36ioVpNauz+8tgu9s1bB3fhkoercMifuaxlUKjUEQ3DDmxTdwuxtUP7a71GoyOGM17hF9V9/dTxYLPMGppsw9VQvHrpocUC4cxtscZBRJrG3av0m1nmGflJHH1ynUsWbVf3pKFqWMxmKZL3zrQhPvHQwfNW+IOMeOfAShFpkJ8CrGZzuD520OdiZDuVgIHQxy8LDMk1RhsvsMtEkR3i6kreajKEtVvnV8JFoASJl6uZt4MgaUVb+PHBk7Mb3T3m6IJPiaZS/mAEcnUMmenVlDfl1i4itzOqj/G+ihRum12Y7NptCtC11mLyWP1tOi+a100fLv7HxdvradoL3ogMSdRANoRau+dPqDe8gZBe2wilvYhU3Ih9nnIEx7dFVmcJaFmNl+S7yMN76CUuAvjuhsr4swRHdHyrtY5ICZTMAAQaa9Yt3Gl98t60aJvEdPgGkBIwItoRgNMNLgI9VaMuLqHmnM/81rUUvrvm30G8g3H5IBM8gN7f6CC0ND4PQIDxSqiP3MURbHODKjJ6gKDwLrLoKdo5vkBVXgAUZL80o="

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

  
