<%@include file="../app/taglibs.jsp"%>																							<html:view title="{title}">																													<html:card>																														<html:card-header>																				carousel-image							</html:card-header>																											<html:card-body>																												<html:tabs>																														<html:tabs-header>																												<html:tabs-tab active="true" labelKey="about" id="tab1"></html:tabs-tab> 												<html:tabs-tab labelKey="attributes" id="tab2"></html:tabs-tab> 														<html:tabs-tab labelKey="demo" id="tab3"></html:tabs-tab> 																<html:tabs-tab labelKey="source" id="tab4"></html:tabs-tab> 														</html:tabs-header> 																										<html:tabs-body> 																												<html:tabs-content active="true" contentOf="tab1">																			<html:alert state="warning">													Renders an carousel image											</html:alert>																											</html:tabs-content>																										<html:tabs-content contentOf="tab2">												<html:table stripe="true" hover="true"><html:thead light="true"><html:tr><html:th><fmt:message key="tag.attribute"/></html:th><html:th><fmt:message key="tag.required"/></html:th><html:th><fmt:message key="tag.type"/></html:th><html:th><fmt:message key="tag.description"/></html:th></html:tr></html:thead><html:tbody><html:tr><html:td>height</html:td><html:td>false</html:td><html:td>java.lang.Integer</html:td><html:td>Indicates the height component</html:td></html:tr><html:tr><html:td>width</html:td><html:td>false</html:td><html:td>java.lang.Integer</html:td><html:td>Indicates the image width</html:td></html:tr><html:tr><html:td>rendered</html:td><html:td>false</html:td><html:td>java.lang.Boolean</html:td><html:td>It indicates if the component should be rendered. Default : true</html:td></html:tr><html:tr><html:td>alt</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>It indicates the alt of image</html:td></html:tr><html:tr><html:td>altKey</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>It indicates the alt key (i18n) of image</html:td></html:tr><html:tr><html:td>cdn</html:td><html:td>false</html:td><html:td>java.lang.Boolean</html:td><html:td>It indicates if the component must be loaded from cdn</html:td></html:tr><html:tr><html:td>url</html:td><html:td>true</html:td><html:td>java.lang.String</html:td><html:td>Indicates the image url</html:td></html:tr></html:tbody></html:table>										</html:tabs-content>																								<html:tabs-content contentOf="tab3">										
			<html:carousel>
				<html:carousel-item active="true" label="Item 1" description="Description 1">
					<html:carousel-image url="https://jslsolucoes.com/wp-content/uploads/logo.png" width="200" height="200" alt="logo"/>
				</html:carousel-item>
				<html:carousel-item label="Item 2" description="Description 2">
					<html:carousel-image url="https://jslsolucoes.com/wp-content/uploads/logo.png" width="200" height="200" alt="logo"/>
				</html:carousel-item>
			</html:carousel> 
												</html:tabs-content>																								<html:tabs-content contentOf="tab4">																					<html:code>																												&lt;html:view&gt;
			&lt;html:carousel&gt;
				&lt;html:carousel-item active="true" label="Item 1" description="Description 1"&gt;
					&lt;html:carousel-image url="https://jslsolucoes.com/wp-content/uploads/logo.png" width="200" height="200" alt="logo"/&gt;
				&lt;/html:carousel-item&gt;
				&lt;html:carousel-item label="Item 2" description="Description 2"&gt;
					&lt;html:carousel-image url="https://jslsolucoes.com/wp-content/uploads/logo.png" width="200" height="200" alt="logo"/&gt;
				&lt;/html:carousel-item&gt;
			&lt;/html:carousel&gt; 
		&lt;/html:view&gt;												</html:code>																									</html:tabs-content>																							</html:tabs-body> 																								</html:tabs>																									</html:card-body>																								</html:card>																									</html:view>																			