<%@include file="../app/taglibs.jsp"%>																							<html:view title="{title}">																													<html:card>																														<html:card-header>																				confirmDialog							</html:card-header>																											<html:card-body>																												<html:tabs>																														<html:tabs-header>																												<html:tabs-tab active="true" labelKey="about" id="tab1"></html:tabs-tab> 												<html:tabs-tab labelKey="attributes" id="tab2"></html:tabs-tab> 														<html:tabs-tab labelKey="demo" id="tab3"></html:tabs-tab> 																<html:tabs-tab labelKey="source" id="tab4"></html:tabs-tab> 														</html:tabs-header> 																										<html:tabs-body> 																												<html:tabs-content active="true" contentOf="tab1">																			<html:alert state="warning">													Renders a dialog modal confirmation											</html:alert>																											</html:tabs-content>																										<html:tabs-content contentOf="tab2">												<html:table stripe="true" hover="true"><html:thead light="true"><html:tr><html:th><fmt:message key="tag.attribute"/></html:th><html:th><fmt:message key="tag.required"/></html:th><html:th><fmt:message key="tag.type"/></html:th><html:th><fmt:message key="tag.description"/></html:th></html:tr></html:thead><html:tbody><html:tr><html:td>label</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>It indicates the label of the title modal</html:td></html:tr><html:tr><html:td>url</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>Indicates the URL to confirm the operation</html:td></html:tr><html:tr><html:td>target</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>Indicates the component target. Default: _self. Options: _blank, _newtab, nomedoiframe</html:td></html:tr><html:tr><html:td>attachTo</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>Indicates the component name that triggers the confirm screen</html:td></html:tr><html:tr><html:td>attachToSelector</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>Indicates the component selector that triggers the confirm screen</html:td></html:tr></html:tbody></html:table>										</html:tabs-content>																								<html:tabs-content contentOf="tab3">										
		    <html:button id="btn1" label="Confirm that ?"/>
			<html:confirm url="#" label="Titulo do modal" attachToSelector="#btn1">
								
			</html:confirm>
												</html:tabs-content>																								<html:tabs-content contentOf="tab4">																					<html:code>																												&lt;html:view&gt;
		    &lt;html:button id="btn1" label="Confirm that ?"/&gt;
			&lt;html:confirm url="#" label="Titulo do modal" attachToSelector="#btn1"&gt;
								
			&lt;/html:confirm&gt;
		&lt;/html:view&gt;												</html:code>																									</html:tabs-content>																							</html:tabs-body> 																								</html:tabs>																									</html:card-body>																								</html:card>																									</html:view>																			