<%@include file="../app/taglibs.jsp"%>										<html:view title="{title}">																	<html:card>																									<html:cardHeader label="dataBlock"/>												<html:cardBody>																								<html:tabPanel>																									<html:tab label="{about}" active="true">																	<html:alert state="warning">																				     	Renders a data block iteration																			</html:alert>																							</html:tab>																									<html:tab label="{attributes}">										<html:table stripe="true" hover="true"><html:tableHeader light="true"><html:tableLine><html:tableHead><fmt:message key="tag.attribute"/></html:tableHead><html:tableHead><fmt:message key="tag.required"/></html:tableHead><html:tableHead><fmt:message key="tag.type"/></html:tableHead><html:tableHead><fmt:message key="tag.description"/></html:tableHead></html:tableLine></html:tableHeader><html:tableBody><html:tableLine><html:tableColumn>data</html:tableColumn><html:tableColumn>true</html:tableColumn><html:tableColumn>java.util.Collection</html:tableColumn><html:tableColumn>It indicates the collection to be iterated by the component</html:tableColumn></html:tableLine><html:tableLine><html:tableColumn>var</html:tableColumn><html:tableColumn>true</html:tableColumn><html:tableColumn>java.lang.String</html:tableColumn><html:tableColumn>It indicates the name of the variable java to be made available the object of iteration</html:tableColumn></html:tableLine><html:tableLine><html:tableColumn>extraSmall</html:tableColumn><html:tableColumn>true</html:tableColumn><html:tableColumn>java.lang.Integer</html:tableColumn><html:tableColumn>Indicates the number of columns to fill to extra small viewport. Options: 1 to 12</html:tableColumn></html:tableLine><html:tableLine><html:tableColumn>small</html:tableColumn><html:tableColumn>false</html:tableColumn><html:tableColumn>java.lang.Integer</html:tableColumn><html:tableColumn>Indicates the number of columns to fill to small viewport. Options: 1 to 12</html:tableColumn></html:tableLine><html:tableLine><html:tableColumn>medium</html:tableColumn><html:tableColumn>false</html:tableColumn><html:tableColumn>java.lang.Integer</html:tableColumn><html:tableColumn>Indicates the number of columns to fill to medium viewport. Options: 1 to 12</html:tableColumn></html:tableLine><html:tableLine><html:tableColumn>large</html:tableColumn><html:tableColumn>false</html:tableColumn><html:tableColumn>java.lang.Integer</html:tableColumn><html:tableColumn>Indicates the number of columns to fill to large viewport. Options: 1 to 12</html:tableColumn></html:tableLine></html:tableBody></html:table>																																	</html:tab>																									<html:tab label="{demo}">																						
			<html:dataBlock limit="12" extraSmall="12" medium="4" small="4" large="1" data="${ persons }" var="person">
				<html:alert state="success">
					${ person.name }
				</html:alert>
			</html:dataBlock>
																									</html:tab>																									<html:tab label="{source}">																					<html:code>																										&lt;html:view&gt;
			&lt;html:dataBlock limit="12" extraSmall="12" medium="4" small="4" large="1" data="\${ persons }" var="person"&gt;
				&lt;html:alert state="success"&gt;
					\${ person.name }
				&lt;/html:alert&gt;
			&lt;/html:dataBlock&gt;
		&lt;/html:view&gt;																					</html:code>																							</html:tab>																								</html:tabPanel>																						</html:cardBody>																						</html:card>																							</html:view>																			