<%@include file="../app/taglibs.jsp"%>																							<html:view title="{title}">																													<html:card>																														<html:card-header>																				datalist							</html:card-header>																											<html:card-body>																												<html:tabs>																														<html:tabs-header>																												<html:tabs-tab active="true" labelKey="about" id="tab1"></html:tabs-tab> 												<html:tabs-tab labelKey="attributes" id="tab2"></html:tabs-tab> 														<html:tabs-tab labelKey="demo" id="tab3"></html:tabs-tab> 																<html:tabs-tab labelKey="source" id="tab4"></html:tabs-tab> 														</html:tabs-header> 																										<html:tabs-body> 																												<html:tabs-content active="true" contentOf="tab1">																			<html:alert state="warning">													Renders a data list component											</html:alert>																											</html:tabs-content>																										<html:tabs-content contentOf="tab2">												<html:table stripe="true" hover="true"><html:thead light="true"><html:tr><html:th><fmt:message key="tag.attribute"/></html:th><html:th><fmt:message key="tag.required"/></html:th><html:th><fmt:message key="tag.type"/></html:th><html:th><fmt:message key="tag.description"/></html:th></html:tr></html:thead><html:tbody><html:tr><html:td>id</html:td><html:td>true</html:td><html:td>java.lang.String</html:td><html:td>Indicates the id for the component</html:td></html:tr><html:tr><html:td>data</html:td><html:td>false</html:td><html:td>java.util.Collection</html:td><html:td>Indicates the collection to be iterated in component</html:td></html:tr><html:tr><html:td>map</html:td><html:td>false</html:td><html:td>java.util.Map</html:td><html:td>Indicates the map to be iterated in component</html:td></html:tr><html:tr><html:td>fixed</html:td><html:td>false</html:td><html:td>java.lang.Boolean</html:td><html:td>Indicates that component has fixed options</html:td></html:tr><html:tr><html:td>var</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>It indicates the name of the variable java to be made available the object of iteration</html:td></html:tr></html:tbody></html:table>										</html:tabs-content>																								<html:tabs-content contentOf="tab3">										
			<html:input name="dl" list="myDatalist1"/>
			<html:datalist id="myDatalist1" data="${ persons }" var="person">
				<html:datalist-option value="${ person.id }">
					${ person.name }
				</html:datalist-option>
			</html:datalist> 										</html:tabs-content>																								<html:tabs-content contentOf="tab4">																					<html:code>																												&lt;html:view&gt;
			&lt;html:input name="dl" list="myDatalist1"/&gt;
			&lt;html:datalist id="myDatalist1" data="\${ persons }" var="person"&gt;
				&lt;html:datalist-option value="\${ person.id }"&gt;
					\${ person.name }
				&lt;/html:datalist-option&gt;
			&lt;/html:datalist&gt; &lt;/html:view&gt;												</html:code>																									</html:tabs-content>																							</html:tabs-body> 																								</html:tabs>																									</html:card-body>																								</html:card>																									</html:view>																			