<%@include file="../app/taglibs.jsp"%>																							<html:view title="{title}">																													<html:card>																														<html:card-header>																				datalist							</html:card-header>																											<html:card-body>																												<html:tabs>																														<html:tabs-header>																												<html:tabs-tab active="true" labelKey="about" id="tab1"></html:tabs-tab> 												<html:tabs-tab labelKey="attributes" id="tab2"></html:tabs-tab> 														<html:tabs-tab labelKey="demo" id="tab3"></html:tabs-tab> 																<html:tabs-tab labelKey="source" id="tab4"></html:tabs-tab> 														</html:tabs-header> 																										<html:tabs-body> 																												<html:tabs-content active="true" contentOf="tab1">																			<html:alert state="warning">													Renders a data list component											</html:alert>																											</html:tabs-content>																										<html:tabs-content contentOf="tab2">												<html:table stripe="true" hover="true"><html:table-header light="true"><html:table-row><html:table-head><fmt:message key="tag.attribute"/></html:table-head><html:table-head><fmt:message key="tag.required"/></html:table-head><html:table-head><fmt:message key="tag.type"/></html:table-head><html:table-head><fmt:message key="tag.description"/></html:table-head></html:table-row></html:table-header><html:table-body><html:table-row><html:table-data>id</html:table-data><html:table-data>true</html:table-data><html:table-data>java.lang.String</html:table-data><html:table-data>Indicates the id for the component</html:table-data></html:table-row><html:table-row><html:table-data>data</html:table-data><html:table-data>false</html:table-data><html:table-data>java.util.Collection</html:table-data><html:table-data>Indicates the collection to be iterated in component</html:table-data></html:table-row><html:table-row><html:table-data>map</html:table-data><html:table-data>false</html:table-data><html:table-data>java.util.Map</html:table-data><html:table-data>Indicates the map to be iterated in component</html:table-data></html:table-row><html:table-row><html:table-data>fixed</html:table-data><html:table-data>false</html:table-data><html:table-data>java.lang.Boolean</html:table-data><html:table-data>Indicates that component has fixed options</html:table-data></html:table-row><html:table-row><html:table-data>var</html:table-data><html:table-data>false</html:table-data><html:table-data>java.lang.String</html:table-data><html:table-data>It indicates the name of the variable java to be made available the object of iteration</html:table-data></html:table-row></html:table-body></html:table>										</html:tabs-content>																								<html:tabs-content contentOf="tab3">										
			<html:input name="dl" list="myDatalist1"/>
			<html:datalist id="myDatalist1" data="${ persons }" var="person">
				<html:datalist-option value="${ person.id }">
					${ person.name }
				</html:datalist-option>
			</html:datalist>
												</html:tabs-content>																								<html:tabs-content contentOf="tab4">																					<html:code>																												&lt;html:view&gt;
			&lt;html:input name="dl" list="myDatalist1"/&gt;
			&lt;html:datalist id="myDatalist1" data="\${ persons }" var="person"&gt;
				&lt;html:datalist-option value="\${ person.id }"&gt;
					\${ person.name }
				&lt;/html:datalist-option&gt;
			&lt;/html:datalist&gt;
		&lt;/html:view&gt;												</html:code>																									</html:tabs-content>																							</html:tabs-body> 																								</html:tabs>																									</html:card-body>																								</html:card>																									</html:view>																			