<%@include file="../app/taglibs.jsp"%>																							<html:view title="{title}">																													<html:card>																														<html:card-header>																				data-block							</html:card-header>																											<html:card-body>																												<html:tabs>																														<html:tabs-header>																												<html:tabs-tab active="true" labelKey="about" id="tab1"></html:tabs-tab> 												<html:tabs-tab labelKey="attributes" id="tab2"></html:tabs-tab> 														<html:tabs-tab labelKey="demo" id="tab3"></html:tabs-tab> 																<html:tabs-tab labelKey="source" id="tab4"></html:tabs-tab> 														</html:tabs-header> 																										<html:tabs-body> 																												<html:tabs-content active="true" contentOf="tab1">																			<html:alert state="warning">													Renders a data block iteration											</html:alert>																											</html:tabs-content>																										<html:tabs-content contentOf="tab2">												<html:table stripe="true" hover="true"><html:thead light="true"><html:tr><html:th><fmt:message key="tag.attribute"/></html:th><html:th><fmt:message key="tag.required"/></html:th><html:th><fmt:message key="tag.type"/></html:th><html:th><fmt:message key="tag.description"/></html:th></html:tr></html:thead><html:tbody><html:tr><html:td>data</html:td><html:td>true</html:td><html:td>java.util.Collection</html:td><html:td>It indicates the collection to be iterated by the component</html:td></html:tr><html:tr><html:td>var</html:td><html:td>true</html:td><html:td>java.lang.String</html:td><html:td>It indicates the name of the variable java to be made available the object of iteration</html:td></html:tr><html:tr><html:td>extraSmall</html:td><html:td>true</html:td><html:td>java.lang.Integer</html:td><html:td>Indicates the number of columns to fill to extra small viewport. Options: 1 to 12</html:td></html:tr><html:tr><html:td>small</html:td><html:td>false</html:td><html:td>java.lang.Integer</html:td><html:td>Indicates the number of columns to fill to small viewport. Options: 1 to 12</html:td></html:tr><html:tr><html:td>medium</html:td><html:td>false</html:td><html:td>java.lang.Integer</html:td><html:td>Indicates the number of columns to fill to medium viewport. Options: 1 to 12</html:td></html:tr><html:tr><html:td>large</html:td><html:td>false</html:td><html:td>java.lang.Integer</html:td><html:td>Indicates the number of columns to fill to large viewport. Options: 1 to 12</html:td></html:tr></html:tbody></html:table>										</html:tabs-content>																								<html:tabs-content contentOf="tab3">										
			<html:data-block extraSmall="12" medium="4" small="4" large="1" data="${ persons }" var="person">
				<html:alert state="success">
					${ person.name }
				</html:alert>
			</html:data-block> 
												</html:tabs-content>																								<html:tabs-content contentOf="tab4">																					<html:code>																												&lt;html:view&gt;
			&lt;html:data-block extraSmall="12" medium="4" small="4" large="1" data="\${ persons }" var="person"&gt;
				&lt;html:alert state="success"&gt;
					\${ person.name }
				&lt;/html:alert&gt;
			&lt;/html:data-block&gt; 
		&lt;/html:view&gt;												</html:code>																									</html:tabs-content>																							</html:tabs-body> 																								</html:tabs>																									</html:card-body>																								</html:card>																									</html:view>																			