<%@include file="../app/taglibs.jsp"%>																							<html:view title="{title}">																													<html:card>																														<html:card-header>																				gridColumn							</html:card-header>																											<html:card-body>																												<html:tabs>																														<html:tabs-header>																												<html:tabs-tab active="true" labelKey="about" id="tab1"></html:tabs-tab> 												<html:tabs-tab labelKey="attributes" id="tab2"></html:tabs-tab> 														<html:tabs-tab labelKey="demo" id="tab3"></html:tabs-tab> 																<html:tabs-tab labelKey="source" id="tab4"></html:tabs-tab> 														</html:tabs-header> 																										<html:tabs-body> 																												<html:tabs-content active="true" contentOf="tab1">																			<html:alert state="warning">													Renders a grid column											</html:alert>																											</html:tabs-content>																										<html:tabs-content contentOf="tab2">												<html:table stripe="true" hover="true"><html:thead light="true"><html:tr><html:th><fmt:message key="tag.attribute"/></html:th><html:th><fmt:message key="tag.required"/></html:th><html:th><fmt:message key="tag.type"/></html:th><html:th><fmt:message key="tag.description"/></html:th></html:tr></html:thead><html:tbody><html:tr><html:td>label</html:td><html:td>false</html:td><html:td>java.util.Collection</html:td><html:td>Indicates the label component</html:td></html:tr><html:tr><html:td>booleanType</html:td><html:td>false</html:td><html:td>java.lang.Boolean</html:td><html:td>Indicates whether the component value is of type boolean</html:td></html:tr><html:tr><html:td>collapsable</html:td><html:td>false</html:td><html:td>java.lang.Boolean</html:td><html:td>It indicates whether the column should be collapsable</html:td></html:tr><html:tr><html:td>exportable</html:td><html:td>false</html:td><html:td>java.lang.Boolean</html:td><html:td>It indicates whether the column should be exported</html:td></html:tr><html:tr><html:td>align</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>Indicates the alignment of the content. Default: left. Options: left, center, right</html:td></html:tr><html:tr><html:td>hideOnViewport</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>Indicates where hide column depending of viewport. Options: xs,md,lg,sm</html:td></html:tr><html:tr><html:td>rendered</html:td><html:td>false</html:td><html:td>java.lang.Boolean</html:td><html:td>It indicates whether the component should be rendered</html:td></html:tr><html:tr><html:td>state</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>Indicates the component state. Default: default. Options: danger, info, success, default</html:td></html:tr></html:tbody></html:table>										</html:tabs-content>																								<html:tabs-content contentOf="tab3">										
			<html:grid label="Pessoas" url="/component/grid" data="${ pessoas }" var="pessoa" noRowText="Não há pessoas disponíveis">
				<html:gridColumn label="Identificação" exportable="true">
					${ pessoa.id }
				</html:gridColumn>
				<html:gridColumn label="Nome" exportable="true">
					${ pessoa.nome }
				</html:gridColumn>
			</html:grid> 										</html:tabs-content>																								<html:tabs-content contentOf="tab4">																					<html:code>																												&lt;html:view&gt;
			&lt;html:grid label="Pessoas" url="/component/grid" data="\${ pessoas }" var="pessoa" noRowText="Não há pessoas disponíveis"&gt;
				&lt;html:gridColumn label="Identificação" exportable="true"&gt;
					\${ pessoa.id }
				&lt;/html:gridColumn&gt;
				&lt;html:gridColumn label="Nome" exportable="true"&gt;
					\${ pessoa.nome }
				&lt;/html:gridColumn&gt;
			&lt;/html:grid&gt; &lt;/html:view&gt;												</html:code>																									</html:tabs-content>																							</html:tabs-body> 																								</html:tabs>																									</html:card-body>																								</html:card>																									</html:view>																			