<%@include file="../app/taglibs.jsp"%>																							<html:view title="{title}">																													<html:card>																														<html:card-header>																				js-event							</html:card-header>																											<html:card-body>																												<html:tabs>																														<html:tabs-header>																												<html:tabs-tab active="true" labelKey="about" id="tab1"></html:tabs-tab> 												<html:tabs-tab labelKey="attributes" id="tab2"></html:tabs-tab> 														<html:tabs-tab labelKey="demo" id="tab3"></html:tabs-tab> 																<html:tabs-tab labelKey="source" id="tab4"></html:tabs-tab> 														</html:tabs-header> 																										<html:tabs-body> 																												<html:tabs-content active="true" contentOf="tab1">																			<html:alert state="warning">													Renders a triggered event for a given component											</html:alert>																											</html:tabs-content>																										<html:tabs-content contentOf="tab2">												<html:table stripe="true" hover="true"><html:thead light="true"><html:tr><html:th><fmt:message key="tag.attribute"/></html:th><html:th><fmt:message key="tag.required"/></html:th><html:th><fmt:message key="tag.type"/></html:th><html:th><fmt:message key="tag.description"/></html:th></html:tr></html:thead><html:tbody><html:tr><html:td>attachTo</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>Indicates the component name to be achieved</html:td></html:tr><html:tr><html:td>attachToSelector</html:td><html:td>false</html:td><html:td>java.lang.String</html:td><html:td>Indicates the component selector that triggers the event</html:td></html:tr><html:tr><html:td>event</html:td><html:td>true</html:td><html:td>java.lang.String</html:td><html:td>Indicates the javascript event to be fired</html:td></html:tr><html:tr><html:td>rendered</html:td><html:td>false</html:td><html:td>java.lang.Boolean</html:td><html:td>It indicates whether the component should be rendered. Default : true</html:td></html:tr></html:tbody></html:table>										</html:tabs-content>																								<html:tabs-content contentOf="tab3">										
			<html:input name="input1" placeholder="Focus in and focus out" />
			<html:js-event attachTo="input1" event="blur">
			    console.log('blur');
			</html:js-event> 
												</html:tabs-content>																								<html:tabs-content contentOf="tab4">																					<html:code>																												&lt;html:view&gt;
			&lt;html:input name="input1" placeholder="Focus in and focus out" /&gt;
			&lt;html:js-event attachTo="input1" event="blur"&gt;
			    console.log('blur');
			&lt;/html:js-event&gt; 
		&lt;/html:view&gt;												</html:code>																									</html:tabs-content>																							</html:tabs-body> 																								</html:tabs>																									</html:card-body>																								</html:card>																									</html:view>																			