<%@include file="../app/taglibs.jsp"  %>																							<html:view title="{title}" template="master">					<html:template render="body">																													<html:card>																														<html:cardHeader>																				dataList							</html:cardHeader>																											<html:cardBody>																												<html:tabs>																														<html:tabsHeader>																												<html:tabsTab active="true" labelKey="about" id="tab1"></html:tabsTab> 												<html:tabsTab labelKey="attributes" id="tab2"></html:tabsTab> 														<html:tabsTab labelKey="demo" id="tab3"></html:tabsTab> 																<html:tabsTab labelKey="source" id="tab4"></html:tabsTab> 														</html:tabsHeader> 																										<html:tabsBody> 																												<html:tabsContent active="true" contentOf="tab1">																			<html:alert state="warning">													Renders a data list component											</html:alert>																											</html:tabsContent>																										<html:tabsContent contentOf="tab2">												<html:table stripe="true" hover="true"><html:tableHeader light="true"><html:tableRow><html:tableHead><fmt:message key="tag.attribute"/></html:tableHead><html:tableHead><fmt:message key="tag.required"/></html:tableHead><html:tableHead><fmt:message key="tag.type"/></html:tableHead><html:tableHead><fmt:message key="tag.description"/></html:tableHead></html:tableRow></html:tableHeader><html:tableBody><html:tableRow><html:tableData>id</html:tableData><html:tableData>true</html:tableData><html:tableData>java.lang.String</html:tableData><html:tableData>Indicates the id for the component</html:tableData></html:tableRow><html:tableRow><html:tableData>data</html:tableData><html:tableData>false</html:tableData><html:tableData>java.lang.Object</html:tableData><html:tableData>It indicates the collection to be iterated by the component. Single objects is converted to Collection using immutable Arrays.asList(...)</html:tableData></html:tableRow><html:tableRow><html:tableData>map</html:tableData><html:tableData>false</html:tableData><html:tableData>java.util.Map</html:tableData><html:tableData>Indicates the map to be iterated in component</html:tableData></html:tableRow><html:tableRow><html:tableData>fixed</html:tableData><html:tableData>false</html:tableData><html:tableData>java.lang.Boolean</html:tableData><html:tableData>Indicates that component has fixed options</html:tableData></html:tableRow><html:tableRow><html:tableData>var</html:tableData><html:tableData>false</html:tableData><html:tableData>java.lang.String</html:tableData><html:tableData>It indicates the name of the variable java to be made available the object of iteration</html:tableData></html:tableRow></html:tableBody></html:table>										</html:tabsContent>																								<html:tabsContent contentOf="tab3">										
			<html:input name="dl" list="myDatalist1"/>
			<html:dataList id="myDatalist1" data="${ persons }" var="person">
				<html:dataListOption value="${ person.id }">
					${ person.name }
				</html:dataListOption>
			</html:dataList>
												</html:tabsContent>																								<html:tabsContent contentOf="tab4">																					<html:code>																												&lt;html:view&gt;
			&lt;html:input name="dl" list="myDatalist1"/&gt;
			&lt;html:dataList id="myDatalist1" data="\${ persons }" var="person"&gt;
				&lt;html:dataListOption value="\${ person.id }"&gt;
					\${ person.name }
				&lt;/html:dataListOption&gt;
			&lt;/html:dataList&gt;
		&lt;/html:view&gt;												</html:code>																									</html:tabsContent>																							</html:tabsBody> 																								</html:tabs>																									</html:cardBody>																								</html:card>																									    </html:template> 																							</html:view>																			